pipelines:
  branches: 
    master:
      - step:
          name: Start
          image: mcr.microsoft.com/dotnet/sdk:5.0
          script:
            - echo "Starting pipeline..."
      - step:
          name: Clean
          image: mcr.microsoft.com/dotnet/sdk:5.0
          script:
            - dotnet restore
            - dotnet clean
      - step:
          name: Build
          image: mcr.microsoft.com/dotnet/sdk:5.0
          script:
            - dotnet build
      - step:
          name: Test
          image: mcr.microsoft.com/dotnet/sdk:5.0
          script:
            - dotnet test
              
      - step:
          name: Install, Unit tests, e2e tests, Build
          image: node:16.10
          caches:
            - node
          script:
            - cd Angular2
            - npm install
            - >
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
              sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
              apt-get update && \
              apt-get install -y google-chrome-stable xvfb procps
            - npm run build:deploy
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: root
                SERVER: vsgate-ssh.dei.isep.ipp.pt
                REMOTE_PATH: '/var/www/html'
                LOCAL_PATH: './dist/*'
                EXTRA_ARGS: '-P 10220'
      - step:
          name: Build and Test
          image: node:10.15.3
          caches:
            - node
          script:
            - cd Post2
            - npm ci
            - npm run build
            - npm run test
