@startuml
autonumber

actor "Jogador" as USER
participant "<<C4:Sistema>>\n:Rede Social" as S

USER -> S : Seleciona pedido de ligação para tomar decisão
activate USER
activate S

S --> USER : Solicita que aceite ou rejeite
deactivate S

USER -> S : Toma a decisão

activate S

S --> USER : Solicita confirmação da decisão
deactivate S

USER -> S : Confirma decisão

activate S

S --> USER : Confirma que o pedido foi aceite ou rejeitado
deactivate S



@enduml