@startuml
left to right direction


circle jogador as "UI Jogador"
circle nao_aut as "UI Utilizador Não autenticado"
circle aut as "UI Utilizador Autenticado"

component social_net as "<<C4:System>> \n Social Network Game"{
    component visual as "<<C4:Container>> \n  Visualização"
    component social as "<<C4:Container>> \n Rede Social"
    component analise as "<<C4:Container>> \n Análise RS"

    circle masterData as "MasterData_RS_API"
    visual -( masterData
    masterData )- social
    visual -0)- analise : ""Análise_RS_API""
    analise - masterData

}


jogador - social_net
nao_aut - social_net
aut -social_net





@enduml