@startuml
autonumber

actor "Jogador" as USER
participant "<<C4:Sistema>>\n:Rede Social" as S

USER -> S : Inicia a consulta em perspetiva da rede
activate USER
activate S

S --> USER : Solicita qual o nível de separação pretendido
deactivate S

USER -> S : Introduz o nível
activate S

S --> USER : Solicita confirmação do nível
deactivate S

USER -> S : Confirma

activate S

S --> USER : Mostra a rede em perspetiva
deactivate S

@enduml