@startuml

actor "Jogador" as jog

participant "<<C4:System>>" as c4

activate jog

jog -> c4: Solicita a lista de utilizadores sugeridos

activate c4
c4 --> jog: apresenta a lista de utlizadores sugeridos \n e solicita que selecione os que pretende como objetivo
deactivate c4

jog -> c4 : seleciona os utilizadores objetivo que pretende ter na sua rede        
activate c4

c4 --> jog : apresenta os utilizadores e solicita confirmação
deactivate c4

jog -> c4 : confirma a seleção
activate c4
c4 --> jog : confirma o sucesso da seleção dos utilizadores objetivo
deactivate c4

deactivate jog


@enduml