@startuml
autonumber

actor "Utilizador Registado" as USER
participant "<<C4:Container>>\nVisualização" as SYSTEM
participant "<<C4:Container>>\nRede Social" as SYSTEM2

activate USER

USER -> SYSTEM: solicita visualização da informação do seu perfil de utilizador

activate SYSTEM

SYSTEM -> SYSTEM2 : GET jogador/{utilizador}

activate SYSTEM2

SYSTEM2 --> SYSTEM : jogador (JSON)

deactivate SYSTEM2

SYSTEM --> USER: mostra perfil de user

deactivate SYSTEM

USER -> SYSTEM: altera dados do perfil

activate SYSTEM

SYSTEM -> SYSTEM : localDataValidation(dados,jogador)

SYSTEM --> USER: solicita confirmação da alteração

deactivate SYSTEM

USER -> SYSTEM: confirma alteração

activate SYSTEM

SYSTEM -> SYSTEM2 : PUT jogador/{utilizador} dto

activate SYSTEM2

SYSTEM2 -> SYSTEM2 : serverDataValidation(dados,jogador)

SYSTEM2 -> SYSTEM2 : saveData(dados,jogador)

SYSTEM2 --> SYSTEM : 202 OK

deactivate SYSTEM2

SYSTEM --> USER: confirma alteração de dados

deactivate SYSTEM

deactivate USER
@enduml